name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['nightly', 'stable']

    steps:
    - uses: actions/checkout@v4

    - name: Install Neovim
      uses: rhymond/setup-neovim@v1
      with:
        neovim-version: ${{ matrix.neovim_version }}

    - name: Install Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1"

    - name: Install Luarocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install luacov

    - name: Run tests
      run: |
        busted --verbose

    - name: Run Stylua
      uses: JohnnyMorganz/stylua-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest
        args: --check .

  doc:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: panvimdoc
      uses: kdheepak/panvimdoc@main
      with:
        vimdoc: todo-lens
        version: "Neovim >= 0.7.0"
        demojify: true
        treesitter: true

    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit_message: "auto: update documentation"
        branch: main 